### ISSUE TITLE
Text BUG

### ISSUE THREAD

**Issue by MountainColdWay** [mikalstill/pngtools#1]
Should add this:
  `num_text=png_get_text(png,info,&text,NULL);`
And the max_text should be delete.
if you want to test this,you should use one png,the thumbnail png!

**Comment by MountainColdWay** [comment]
the pnginfo.c

**Comment by mikalstill** [comment]
I am unsure what these words mean. Could you send a PR please?

**Comment by MountainColdWay** [comment]
ok,i have send a pr

**Comment by mikalstill** [comment]
Fixed by #2. Sorry for being so slow.
